---
- hosts: dev
  become: yes
  become_user: root
  gather_facts: true
  
  tasks:
    - name: run script
      shell: /bin/sh /root/.jenkins/workspace/test-cdl/cdl.sh


- hosts: stage
  become: yes
  become_user: root
  gather_facts: true

  tasks:
    - name: run script
      shell: /bin/sh $WOSKSPACE/cdl.sh
