---
- hosts: dev
  become: yes
  become_user: root
  gather_facts: true
  
  tasks:
    - name: run script
      shell: /usr/bin/sh $WORKSPACE/cdl.sh


- hosts: stage
  become: yes
  become_user: root
  gather_facts: true

  tasks:
    - name: run script
      shell: /usr/bin/sh $WOSKSPACE/cdl.sh
